name = "contact-form-worker"
main = "src/index.js"
compatibility_date = "2026-04-19"

[vars]
ALLOWED_ORIGIN = "https://www.brandonanhorn.com"
RESEND_FROM = "noreply@mail.brandonanhorn.com"
RESEND_TO = "ai.brandonanhorn@gmail.com"
